on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: "Build & Release Website"
jobs:
  hosting:
    name: Build & Release Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
          channel: "stable"

      # Build Website
      - name: Build Website
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release
        working-directory: ./

      # Deploy Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.RELEASE_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_QUOTES_WEB_PUBLIC }}'
          channelId: live
          projectId: quotes-web-public